### ISSUE TITLE
PacketRaknetAck IllegalArgumentException

### ISSUE THREAD

**Issue by Serializator** [PocketServer/PocketServer#74] opened 2016-01-30 15:01 UTC
Stack trace:
http://pastebin.com/QYcfrY3C

How to reproduce:
- Log into the server.
- Log out of the server.
- Log into the server.

**Comment by TheLightMC** [comment] 2016-01-31 04:39
Fixed in https://github.com/PocketServer/PocketServer/commit/7c26b2903cc43b8e345980ec2b8d4b8d5cbdd641 . Oddly enough the NACK still occurs, not sure why. I'll have to do further testing to identify the cause of it. The server and client both allow the login regardless so I'm going to put it on the shelf for awhile.

**Closed by TheLightMC** 2016-01-31 04:39 UTC
